/* Auto-generated by genmsg_cpp for file /home/diogo/Documents/DD2425_2013/Project/HandFollow/msg/vw.msg */
#ifndef HANDFOLLOW_MESSAGE_VW_H
#define HANDFOLLOW_MESSAGE_VW_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace HandFollow
{
template <class ContainerAllocator>
struct vw_ {
  typedef vw_<ContainerAllocator> Type;

  vw_()
  : header()
  , v(0.0)
  , w(0.0)
  {
  }

  vw_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , v(0.0)
  , w(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _v_type;
  float v;

  typedef float _w_type;
  float w;


  typedef boost::shared_ptr< ::HandFollow::vw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::HandFollow::vw_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct vw
typedef  ::HandFollow::vw_<std::allocator<void> > vw;

typedef boost::shared_ptr< ::HandFollow::vw> vwPtr;
typedef boost::shared_ptr< ::HandFollow::vw const> vwConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::HandFollow::vw_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::HandFollow::vw_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace HandFollow

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::HandFollow::vw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::HandFollow::vw_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::HandFollow::vw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c9739f01512ce85d8ac1ccdd6bde650b";
  }

  static const char* value(const  ::HandFollow::vw_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc9739f01512ce85dULL;
  static const uint64_t static_value2 = 0x8ac1ccdd6bde650bULL;
};

template<class ContainerAllocator>
struct DataType< ::HandFollow::vw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "HandFollow/vw";
  }

  static const char* value(const  ::HandFollow::vw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::HandFollow::vw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 v\n\
float32 w\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::HandFollow::vw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::HandFollow::vw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::HandFollow::vw_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::HandFollow::vw_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.v);
    stream.next(m.w);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct vw_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::HandFollow::vw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::HandFollow::vw_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HANDFOLLOW_MESSAGE_VW_H

