"""autogenerated by genpy from core_control_motor/pid.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class pid(genpy.Message):
  _md5sum = "4e1de776987ab9bbada7aae4944a912e"
  _type = "core_control_motor/pid"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 p1
float32 p2
float32 i1
float32 i2
float32 d1
float32 d2

"""
  __slots__ = ['p1','p2','i1','i2','d1','d2']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       p1,p2,i1,i2,d1,d2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pid, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.p1 is None:
        self.p1 = 0.
      if self.p2 is None:
        self.p2 = 0.
      if self.i1 is None:
        self.i1 = 0.
      if self.i2 is None:
        self.i2 = 0.
      if self.d1 is None:
        self.d1 = 0.
      if self.d2 is None:
        self.d2 = 0.
    else:
      self.p1 = 0.
      self.p2 = 0.
      self.i1 = 0.
      self.i2 = 0.
      self.d1 = 0.
      self.d2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.p1, _x.p2, _x.i1, _x.i2, _x.d1, _x.d2))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.p1, _x.p2, _x.i1, _x.i2, _x.d1, _x.d2,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.p1, _x.p2, _x.i1, _x.i2, _x.d1, _x.d2))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.p1, _x.p2, _x.i1, _x.i2, _x.d1, _x.d2,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6f = struct.Struct("<6f")
